"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class VariablesFeaturesSet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_QUANTITATIVE_FIELD_NUMBER: builtins.int
    MISSING_ENTRIES_RATIO_FIELD_NUMBER: builtins.int
    is_quantitative: builtins.bool
    missing_entries_ratio: builtins.float
    def __init__(
        self,
        *,
        is_quantitative: builtins.bool = ...,
        missing_entries_ratio: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["is_quantitative", b"is_quantitative", "missing_entries_ratio", b"missing_entries_ratio"]) -> None: ...

global___VariablesFeaturesSet = VariablesFeaturesSet

class DataFeaturesSet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class VariablesFeaturesSetEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___VariablesFeaturesSet: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___VariablesFeaturesSet | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    ROWS_COUNT_FIELD_NUMBER: builtins.int
    VARIABLES_COUNT_FIELD_NUMBER: builtins.int
    RATIO_OF_CONTINOUS_VARIABLES_FIELD_NUMBER: builtins.int
    IS_RESPONSE_QUANTITATIVE_FIELD_NUMBER: builtins.int
    IS_RESPONSE_DICHOTOMOUS_FIELD_NUMBER: builtins.int
    VARIABLES_FEATURES_SET_FIELD_NUMBER: builtins.int
    rows_count: builtins.int
    variables_count: builtins.int
    ratio_of_continous_variables: builtins.float
    is_response_quantitative: builtins.bool
    is_response_dichotomous: builtins.bool
    @property
    def variables_features_set(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___VariablesFeaturesSet]: ...
    def __init__(
        self,
        *,
        rows_count: builtins.int = ...,
        variables_count: builtins.int = ...,
        ratio_of_continous_variables: builtins.float = ...,
        is_response_quantitative: builtins.bool = ...,
        is_response_dichotomous: builtins.bool = ...,
        variables_features_set: collections.abc.Mapping[builtins.str, global___VariablesFeaturesSet] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["is_response_dichotomous", b"is_response_dichotomous", "is_response_quantitative", b"is_response_quantitative", "ratio_of_continous_variables", b"ratio_of_continous_variables", "rows_count", b"rows_count", "variables_count", b"variables_count", "variables_features_set", b"variables_features_set"]) -> None: ...

global___DataFeaturesSet = DataFeaturesSet

class GetFeaturesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATASET_ID_FIELD_NUMBER: builtins.int
    dataset_id: builtins.str
    def __init__(
        self,
        *,
        dataset_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["dataset_id", b"dataset_id"]) -> None: ...

global___GetFeaturesRequest = GetFeaturesRequest

class ExtractFeaturesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATASET_ID_FIELD_NUMBER: builtins.int
    RESPONSE_NAME_FIELD_NUMBER: builtins.int
    SKIP_FEATURES_FIELD_NUMBER: builtins.int
    dataset_id: builtins.str
    response_name: builtins.str
    @property
    def skip_features(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        dataset_id: builtins.str = ...,
        response_name: builtins.str = ...,
        skip_features: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["dataset_id", b"dataset_id", "response_name", b"response_name", "skip_features", b"skip_features"]) -> None: ...

global___ExtractFeaturesRequest = ExtractFeaturesRequest
