# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: features_extractor_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n features_extractor_service.proto\"N\n\x14VariablesFeaturesSet\x12\x17\n\x0fis_quantitative\x18\x01 \x01(\x08\x12\x1d\n\x15missing_entries_ratio\x18\x02 \x01(\x02\"\xc7\x02\n\x0f\x44\x61taFeaturesSet\x12\x12\n\nrows_count\x18\x01 \x01(\x05\x12\x17\n\x0fvariables_count\x18\x02 \x01(\x05\x12$\n\x1cratio_of_continous_variables\x18\x03 \x01(\x02\x12 \n\x18is_response_quantitative\x18\x04 \x01(\x08\x12\x1f\n\x17is_response_dichotomous\x18\x05 \x01(\x08\x12J\n\x16variables_features_set\x18\x06 \x03(\x0b\x32*.DataFeaturesSet.VariablesFeaturesSetEntry\x1aR\n\x19VariablesFeaturesSetEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.VariablesFeaturesSet:\x02\x38\x01\"(\n\x12GetFeaturesRequest\x12\x12\n\ndataset_id\x18\x01 \x01(\t\"Z\n\x16\x45xtractFeaturesRequest\x12\x12\n\ndataset_id\x18\x01 \x01(\t\x12\x15\n\rresponse_name\x18\x02 \x01(\t\x12\x15\n\rskip_features\x18\x03 \x03(\t2\x8e\x01\n\x18\x46\x65\x61turesExtractorService\x12\x34\n\x0bGetFeatures\x12\x13.GetFeaturesRequest\x1a\x10.DataFeaturesSet\x12<\n\x0f\x45xtractFeatures\x12\x17.ExtractFeaturesRequest\x1a\x10.DataFeaturesSetb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'features_extractor_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATAFEATURESSET_VARIABLESFEATURESSETENTRY._options = None
  _DATAFEATURESSET_VARIABLESFEATURESSETENTRY._serialized_options = b'8\001'
  _VARIABLESFEATURESSET._serialized_start=36
  _VARIABLESFEATURESSET._serialized_end=114
  _DATAFEATURESSET._serialized_start=117
  _DATAFEATURESSET._serialized_end=444
  _DATAFEATURESSET_VARIABLESFEATURESSETENTRY._serialized_start=362
  _DATAFEATURESSET_VARIABLESFEATURESSETENTRY._serialized_end=444
  _GETFEATURESREQUEST._serialized_start=446
  _GETFEATURESREQUEST._serialized_end=486
  _EXTRACTFEATURESREQUEST._serialized_start=488
  _EXTRACTFEATURESREQUEST._serialized_end=578
  _FEATURESEXTRACTORSERVICE._serialized_start=581
  _FEATURESEXTRACTORSERVICE._serialized_end=723
# @@protoc_insertion_point(module_scope)
